// Generated by rstantools.  Do not edit by hand.

/*
    titertools is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    titertools is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with titertools.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0
#include <stan/model/model_header.hpp>
namespace model_compare_crossreactivity_breadth_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_compare_crossreactivity_breadth");
    reader.add_event(2, 2, "include", "/functions/normal_int_censored_likelihood.stan");
    reader.add_event(2, 0, "start", "/functions/normal_int_censored_likelihood.stan");
    reader.add_event(41, 39, "end", "/functions/normal_int_censored_likelihood.stan");
    reader.add_event(41, 3, "restart", "model_compare_crossreactivity_breadth");
    reader.add_event(100, 60, "end", "model_compare_crossreactivity_breadth");
    return reader;
}
template <typename T0__, typename T1__, typename T2__, typename T3__>
typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type
normal_int_censored_likelihood(const T0__& lower_lim,
                                   const T1__& upper_lim,
                                   const T2__& mu,
                                   const T3__& sigma, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 6;
        local_scalar_t__ result(DUMMY_VAR__);
        (void) result;  // dummy to suppress unused var warning
        stan::math::initialize(result, DUMMY_VAR__);
        stan::math::fill(result, DUMMY_VAR__);
        current_statement_begin__ = 8;
        if (as_bool((primitive_value(is_inf(lower_lim)) && primitive_value(is_inf(upper_lim))))) {
            current_statement_begin__ = 10;
            stan::math::assign(result, 0);
        } else if (as_bool(logical_eq(lower_lim, upper_lim))) {
            current_statement_begin__ = 14;
            stan::math::assign(result, normal_log(lower_lim, mu, sigma));
        } else if (as_bool((primitive_value(logical_negation(is_inf(lower_lim))) && primitive_value(logical_negation(is_inf(upper_lim)))))) {
            current_statement_begin__ = 20;
            stan::math::assign(result, log_diff_exp(normal_cdf_log(upper_lim, mu, sigma), normal_cdf_log(lower_lim, mu, sigma)));
        } else if (as_bool((primitive_value(logical_negation(is_inf(lower_lim))) && primitive_value(is_inf(upper_lim))))) {
            current_statement_begin__ = 27;
            stan::math::assign(result, normal_ccdf_log(lower_lim, mu, sigma));
        } else if (as_bool((primitive_value(is_inf(lower_lim)) && primitive_value(logical_negation(is_inf(upper_lim)))))) {
            current_statement_begin__ = 33;
            stan::math::assign(result, normal_cdf_log(upper_lim, mu, sigma));
        }
        current_statement_begin__ = 39;
        return stan::math::promote_scalar<fun_return_scalar_t__>(result);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct normal_int_censored_likelihood_functor__ {
    template <typename T0__, typename T1__, typename T2__, typename T3__>
        typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type
    operator()(const T0__& lower_lim,
                                   const T1__& upper_lim,
                                   const T2__& mu,
                                   const T3__& sigma, std::ostream* pstream__) const {
        return normal_int_censored_likelihood(lower_lim, upper_lim, mu, sigma, pstream__);
    }
};
#include <stan_meta_header.hpp>
class model_compare_crossreactivity_breadth
  : public stan::model::model_base_crtp<model_compare_crossreactivity_breadth> {
private:
        int N;
        int N_ags;
        int N_srs;
        int N_sr_groups;
        vector_d upper_logtiter_lims;
        vector_d lower_logtiter_lims;
        vector_d upper_homologous_logtiter_lims;
        vector_d lower_homologous_logtiter_lims;
        std::vector<int> ags;
        std::vector<int> srs;
        std::vector<int> sr_groups;
public:
    model_compare_crossreactivity_breadth(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_compare_crossreactivity_breadth(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_compare_crossreactivity_breadth_namespace::model_compare_crossreactivity_breadth";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 45;
            context__.validate_dims("data initialization", "N", "int", context__.to_vec());
            N = int(0);
            vals_i__ = context__.vals_i("N");
            pos__ = 0;
            N = vals_i__[pos__++];
            check_greater_or_equal(function__, "N", N, 0);
            current_statement_begin__ = 46;
            context__.validate_dims("data initialization", "N_ags", "int", context__.to_vec());
            N_ags = int(0);
            vals_i__ = context__.vals_i("N_ags");
            pos__ = 0;
            N_ags = vals_i__[pos__++];
            check_greater_or_equal(function__, "N_ags", N_ags, 0);
            current_statement_begin__ = 47;
            context__.validate_dims("data initialization", "N_srs", "int", context__.to_vec());
            N_srs = int(0);
            vals_i__ = context__.vals_i("N_srs");
            pos__ = 0;
            N_srs = vals_i__[pos__++];
            check_greater_or_equal(function__, "N_srs", N_srs, 0);
            current_statement_begin__ = 48;
            context__.validate_dims("data initialization", "N_sr_groups", "int", context__.to_vec());
            N_sr_groups = int(0);
            vals_i__ = context__.vals_i("N_sr_groups");
            pos__ = 0;
            N_sr_groups = vals_i__[pos__++];
            check_greater_or_equal(function__, "N_sr_groups", N_sr_groups, 0);
            current_statement_begin__ = 49;
            validate_non_negative_index("upper_logtiter_lims", "N", N);
            context__.validate_dims("data initialization", "upper_logtiter_lims", "vector_d", context__.to_vec(N));
            upper_logtiter_lims = Eigen::Matrix<double, Eigen::Dynamic, 1>(N);
            vals_r__ = context__.vals_r("upper_logtiter_lims");
            pos__ = 0;
            size_t upper_logtiter_lims_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < upper_logtiter_lims_j_1_max__; ++j_1__) {
                upper_logtiter_lims(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 50;
            validate_non_negative_index("lower_logtiter_lims", "N", N);
            context__.validate_dims("data initialization", "lower_logtiter_lims", "vector_d", context__.to_vec(N));
            lower_logtiter_lims = Eigen::Matrix<double, Eigen::Dynamic, 1>(N);
            vals_r__ = context__.vals_r("lower_logtiter_lims");
            pos__ = 0;
            size_t lower_logtiter_lims_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < lower_logtiter_lims_j_1_max__; ++j_1__) {
                lower_logtiter_lims(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 51;
            validate_non_negative_index("upper_homologous_logtiter_lims", "N_srs", N_srs);
            context__.validate_dims("data initialization", "upper_homologous_logtiter_lims", "vector_d", context__.to_vec(N_srs));
            upper_homologous_logtiter_lims = Eigen::Matrix<double, Eigen::Dynamic, 1>(N_srs);
            vals_r__ = context__.vals_r("upper_homologous_logtiter_lims");
            pos__ = 0;
            size_t upper_homologous_logtiter_lims_j_1_max__ = N_srs;
            for (size_t j_1__ = 0; j_1__ < upper_homologous_logtiter_lims_j_1_max__; ++j_1__) {
                upper_homologous_logtiter_lims(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 52;
            validate_non_negative_index("lower_homologous_logtiter_lims", "N_srs", N_srs);
            context__.validate_dims("data initialization", "lower_homologous_logtiter_lims", "vector_d", context__.to_vec(N_srs));
            lower_homologous_logtiter_lims = Eigen::Matrix<double, Eigen::Dynamic, 1>(N_srs);
            vals_r__ = context__.vals_r("lower_homologous_logtiter_lims");
            pos__ = 0;
            size_t lower_homologous_logtiter_lims_j_1_max__ = N_srs;
            for (size_t j_1__ = 0; j_1__ < lower_homologous_logtiter_lims_j_1_max__; ++j_1__) {
                lower_homologous_logtiter_lims(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 53;
            validate_non_negative_index("ags", "N", N);
            context__.validate_dims("data initialization", "ags", "int", context__.to_vec(N));
            ags = std::vector<int>(N, int(0));
            vals_i__ = context__.vals_i("ags");
            pos__ = 0;
            size_t ags_k_0_max__ = N;
            for (size_t k_0__ = 0; k_0__ < ags_k_0_max__; ++k_0__) {
                ags[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 54;
            validate_non_negative_index("srs", "N", N);
            context__.validate_dims("data initialization", "srs", "int", context__.to_vec(N));
            srs = std::vector<int>(N, int(0));
            vals_i__ = context__.vals_i("srs");
            pos__ = 0;
            size_t srs_k_0_max__ = N;
            for (size_t k_0__ = 0; k_0__ < srs_k_0_max__; ++k_0__) {
                srs[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 55;
            validate_non_negative_index("sr_groups", "N", N);
            context__.validate_dims("data initialization", "sr_groups", "int", context__.to_vec(N));
            sr_groups = std::vector<int>(N, int(0));
            vals_i__ = context__.vals_i("sr_groups");
            pos__ = 0;
            size_t sr_groups_k_0_max__ = N;
            for (size_t k_0__ = 0; k_0__ < sr_groups_k_0_max__; ++k_0__) {
                sr_groups[k_0__] = vals_i__[pos__++];
            }
            // initialize transformed data variables
            // execute transformed data statements
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 59;
            validate_non_negative_index("sr_group_slopes", "(N_sr_groups - 1)", (N_sr_groups - 1));
            num_params_r__ += (N_sr_groups - 1);
            current_statement_begin__ = 60;
            validate_non_negative_index("ag_folddrops", "N_ags", N_ags);
            num_params_r__ += N_ags;
            current_statement_begin__ = 61;
            num_params_r__ += 1;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_compare_crossreactivity_breadth() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 59;
        if (!(context__.contains_r("sr_group_slopes")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable sr_group_slopes missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("sr_group_slopes");
        pos__ = 0U;
        validate_non_negative_index("sr_group_slopes", "(N_sr_groups - 1)", (N_sr_groups - 1));
        context__.validate_dims("parameter initialization", "sr_group_slopes", "vector_d", context__.to_vec((N_sr_groups - 1)));
        Eigen::Matrix<double, Eigen::Dynamic, 1> sr_group_slopes((N_sr_groups - 1));
        size_t sr_group_slopes_j_1_max__ = (N_sr_groups - 1);
        for (size_t j_1__ = 0; j_1__ < sr_group_slopes_j_1_max__; ++j_1__) {
            sr_group_slopes(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_lub_unconstrain(0.01, 2, sr_group_slopes);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable sr_group_slopes: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 60;
        if (!(context__.contains_r("ag_folddrops")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable ag_folddrops missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("ag_folddrops");
        pos__ = 0U;
        validate_non_negative_index("ag_folddrops", "N_ags", N_ags);
        context__.validate_dims("parameter initialization", "ag_folddrops", "vector_d", context__.to_vec(N_ags));
        Eigen::Matrix<double, Eigen::Dynamic, 1> ag_folddrops(N_ags);
        size_t ag_folddrops_j_1_max__ = N_ags;
        for (size_t j_1__ = 0; j_1__ < ag_folddrops_j_1_max__; ++j_1__) {
            ag_folddrops(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(ag_folddrops);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable ag_folddrops: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 61;
        if (!(context__.contains_r("logtiter_error_sigma")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable logtiter_error_sigma missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("logtiter_error_sigma");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "logtiter_error_sigma", "double", context__.to_vec());
        double logtiter_error_sigma(0);
        logtiter_error_sigma = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, logtiter_error_sigma);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable logtiter_error_sigma: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 59;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> sr_group_slopes;
            (void) sr_group_slopes;  // dummy to suppress unused var warning
            if (jacobian__)
                sr_group_slopes = in__.vector_lub_constrain(0.01, 2, (N_sr_groups - 1), lp__);
            else
                sr_group_slopes = in__.vector_lub_constrain(0.01, 2, (N_sr_groups - 1));
            current_statement_begin__ = 60;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> ag_folddrops;
            (void) ag_folddrops;  // dummy to suppress unused var warning
            if (jacobian__)
                ag_folddrops = in__.vector_constrain(N_ags, lp__);
            else
                ag_folddrops = in__.vector_constrain(N_ags);
            current_statement_begin__ = 61;
            local_scalar_t__ logtiter_error_sigma;
            (void) logtiter_error_sigma;  // dummy to suppress unused var warning
            if (jacobian__)
                logtiter_error_sigma = in__.scalar_lb_constrain(0, lp__);
            else
                logtiter_error_sigma = in__.scalar_lb_constrain(0);
            // model body
            {
            current_statement_begin__ = 67;
            local_scalar_t__ folddrop(DUMMY_VAR__);
            (void) folddrop;  // dummy to suppress unused var warning
            stan::math::initialize(folddrop, DUMMY_VAR__);
            stan::math::fill(folddrop, DUMMY_VAR__);
            current_statement_begin__ = 68;
            local_scalar_t__ sr_group_slope(DUMMY_VAR__);
            (void) sr_group_slope;  // dummy to suppress unused var warning
            stan::math::initialize(sr_group_slope, DUMMY_VAR__);
            stan::math::fill(sr_group_slope, DUMMY_VAR__);
            current_statement_begin__ = 71;
            lp_accum__.add(normal_log<propto__>(ag_folddrops, 0, 1000));
            current_statement_begin__ = 74;
            for (int i = 1; i <= N; ++i) {
                {
                current_statement_begin__ = 77;
                int ag(0);
                (void) ag;  // dummy to suppress unused var warning
                stan::math::fill(ag, std::numeric_limits<int>::min());
                stan::math::assign(ag,get_base1(ags, i, "ags", 1));
                current_statement_begin__ = 78;
                int sr(0);
                (void) sr;  // dummy to suppress unused var warning
                stan::math::fill(sr, std::numeric_limits<int>::min());
                stan::math::assign(sr,get_base1(srs, i, "srs", 1));
                current_statement_begin__ = 79;
                int sr_group(0);
                (void) sr_group;  // dummy to suppress unused var warning
                stan::math::fill(sr_group, std::numeric_limits<int>::min());
                stan::math::assign(sr_group,get_base1(sr_groups, i, "sr_groups", 1));
                current_statement_begin__ = 82;
                if (as_bool(logical_eq(sr_group, 1))) {
                    current_statement_begin__ = 82;
                    stan::math::assign(sr_group_slope, 1);
                } else {
                    current_statement_begin__ = 83;
                    stan::math::assign(sr_group_slope, get_base1(sr_group_slopes, (sr_group - 1), "sr_group_slopes", 1));
                }
                current_statement_begin__ = 86;
                stan::math::assign(folddrop, (get_base1(ag_folddrops, ag, "ag_folddrops", 1) * sr_group_slope));
                current_statement_begin__ = 89;
                lp_accum__.add(normal_int_censored_likelihood((get_base1(lower_logtiter_lims, i, "lower_logtiter_lims", 1) - get_base1(upper_homologous_logtiter_lims, sr, "upper_homologous_logtiter_lims", 1)), (get_base1(upper_logtiter_lims, i, "upper_logtiter_lims", 1) - get_base1(lower_homologous_logtiter_lims, sr, "lower_homologous_logtiter_lims", 1)), folddrop, logtiter_error_sigma, pstream__));
                }
            }
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("sr_group_slopes");
        names__.push_back("ag_folddrops");
        names__.push_back("logtiter_error_sigma");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back((N_sr_groups - 1));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N_ags);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_compare_crossreactivity_breadth_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        Eigen::Matrix<double, Eigen::Dynamic, 1> sr_group_slopes = in__.vector_lub_constrain(0.01, 2, (N_sr_groups - 1));
        size_t sr_group_slopes_j_1_max__ = (N_sr_groups - 1);
        for (size_t j_1__ = 0; j_1__ < sr_group_slopes_j_1_max__; ++j_1__) {
            vars__.push_back(sr_group_slopes(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> ag_folddrops = in__.vector_constrain(N_ags);
        size_t ag_folddrops_j_1_max__ = N_ags;
        for (size_t j_1__ = 0; j_1__ < ag_folddrops_j_1_max__; ++j_1__) {
            vars__.push_back(ag_folddrops(j_1__));
        }
        double logtiter_error_sigma = in__.scalar_lb_constrain(0);
        vars__.push_back(logtiter_error_sigma);
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            if (!include_gqs__ && !include_tparams__) return;
            if (!include_gqs__) return;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    std::string model_name() const {
        return "model_compare_crossreactivity_breadth";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t sr_group_slopes_j_1_max__ = (N_sr_groups - 1);
        for (size_t j_1__ = 0; j_1__ < sr_group_slopes_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "sr_group_slopes" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t ag_folddrops_j_1_max__ = N_ags;
        for (size_t j_1__ = 0; j_1__ < ag_folddrops_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "ag_folddrops" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "logtiter_error_sigma";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t sr_group_slopes_j_1_max__ = (N_sr_groups - 1);
        for (size_t j_1__ = 0; j_1__ < sr_group_slopes_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "sr_group_slopes" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t ag_folddrops_j_1_max__ = N_ags;
        for (size_t j_1__ = 0; j_1__ < ag_folddrops_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "ag_folddrops" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "logtiter_error_sigma";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
    }
}; // model
}  // namespace
typedef model_compare_crossreactivity_breadth_namespace::model_compare_crossreactivity_breadth stan_model;
#ifndef USING_R
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
#endif
#endif
