// Generated by rstantools.  Do not edit by hand.

/*
    titertools is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    titertools is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with titertools.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0
#include <stan/model/model_header.hpp>
namespace model_lm_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_lm");
    reader.add_event(2, 2, "include", "/functions/normal_int_censored_likelihood.stan");
    reader.add_event(2, 0, "start", "/functions/normal_int_censored_likelihood.stan");
    reader.add_event(41, 39, "end", "/functions/normal_int_censored_likelihood.stan");
    reader.add_event(41, 3, "restart", "model_lm");
    reader.add_event(102, 62, "end", "model_lm");
    return reader;
}
template <typename T0__, typename T1__, typename T2__, typename T3__>
typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type
normal_int_censored_likelihood(const T0__& lower_lim,
                                   const T1__& upper_lim,
                                   const T2__& mu,
                                   const T3__& sigma, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 6;
        local_scalar_t__ result(DUMMY_VAR__);
        (void) result;  // dummy to suppress unused var warning
        stan::math::initialize(result, DUMMY_VAR__);
        stan::math::fill(result, DUMMY_VAR__);
        current_statement_begin__ = 8;
        if (as_bool((primitive_value(is_inf(lower_lim)) && primitive_value(is_inf(upper_lim))))) {
            current_statement_begin__ = 10;
            stan::math::assign(result, 0);
        } else if (as_bool(logical_eq(lower_lim, upper_lim))) {
            current_statement_begin__ = 14;
            stan::math::assign(result, normal_log(lower_lim, mu, sigma));
        } else if (as_bool((primitive_value(logical_negation(is_inf(lower_lim))) && primitive_value(logical_negation(is_inf(upper_lim)))))) {
            current_statement_begin__ = 20;
            stan::math::assign(result, log_diff_exp(normal_cdf_log(upper_lim, mu, sigma), normal_cdf_log(lower_lim, mu, sigma)));
        } else if (as_bool((primitive_value(logical_negation(is_inf(lower_lim))) && primitive_value(is_inf(upper_lim))))) {
            current_statement_begin__ = 27;
            stan::math::assign(result, normal_ccdf_log(lower_lim, mu, sigma));
        } else if (as_bool((primitive_value(is_inf(lower_lim)) && primitive_value(logical_negation(is_inf(upper_lim)))))) {
            current_statement_begin__ = 33;
            stan::math::assign(result, normal_cdf_log(upper_lim, mu, sigma));
        }
        current_statement_begin__ = 39;
        return stan::math::promote_scalar<fun_return_scalar_t__>(result);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct normal_int_censored_likelihood_functor__ {
    template <typename T0__, typename T1__, typename T2__, typename T3__>
        typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type
    operator()(const T0__& lower_lim,
                                   const T1__& upper_lim,
                                   const T2__& mu,
                                   const T3__& sigma, std::ostream* pstream__) const {
        return normal_int_censored_likelihood(lower_lim, upper_lim, mu, sigma, pstream__);
    }
};
#include <stan_meta_header.hpp>
class model_lm
  : public stan::model::model_base_crtp<model_lm> {
private:
        int N;
        vector_d upper_lims1;
        vector_d lower_lims1;
        vector_d upper_lims2;
        vector_d lower_lims2;
        double intercept_prior_mu;
        double intercept_prior_sigma;
        double slope_prior_mu;
        double slope_prior_sigma;
        double sigma_prior_alpha;
        double sigma_prior_beta;
public:
    model_lm(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_lm(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_lm_namespace::model_lm";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 45;
            context__.validate_dims("data initialization", "N", "int", context__.to_vec());
            N = int(0);
            vals_i__ = context__.vals_i("N");
            pos__ = 0;
            N = vals_i__[pos__++];
            check_greater_or_equal(function__, "N", N, 1);
            current_statement_begin__ = 46;
            validate_non_negative_index("upper_lims1", "N", N);
            context__.validate_dims("data initialization", "upper_lims1", "vector_d", context__.to_vec(N));
            upper_lims1 = Eigen::Matrix<double, Eigen::Dynamic, 1>(N);
            vals_r__ = context__.vals_r("upper_lims1");
            pos__ = 0;
            size_t upper_lims1_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < upper_lims1_j_1_max__; ++j_1__) {
                upper_lims1(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 47;
            validate_non_negative_index("lower_lims1", "N", N);
            context__.validate_dims("data initialization", "lower_lims1", "vector_d", context__.to_vec(N));
            lower_lims1 = Eigen::Matrix<double, Eigen::Dynamic, 1>(N);
            vals_r__ = context__.vals_r("lower_lims1");
            pos__ = 0;
            size_t lower_lims1_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < lower_lims1_j_1_max__; ++j_1__) {
                lower_lims1(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 48;
            validate_non_negative_index("upper_lims2", "N", N);
            context__.validate_dims("data initialization", "upper_lims2", "vector_d", context__.to_vec(N));
            upper_lims2 = Eigen::Matrix<double, Eigen::Dynamic, 1>(N);
            vals_r__ = context__.vals_r("upper_lims2");
            pos__ = 0;
            size_t upper_lims2_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < upper_lims2_j_1_max__; ++j_1__) {
                upper_lims2(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 49;
            validate_non_negative_index("lower_lims2", "N", N);
            context__.validate_dims("data initialization", "lower_lims2", "vector_d", context__.to_vec(N));
            lower_lims2 = Eigen::Matrix<double, Eigen::Dynamic, 1>(N);
            vals_r__ = context__.vals_r("lower_lims2");
            pos__ = 0;
            size_t lower_lims2_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < lower_lims2_j_1_max__; ++j_1__) {
                lower_lims2(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 50;
            context__.validate_dims("data initialization", "intercept_prior_mu", "double", context__.to_vec());
            intercept_prior_mu = double(0);
            vals_r__ = context__.vals_r("intercept_prior_mu");
            pos__ = 0;
            intercept_prior_mu = vals_r__[pos__++];
            current_statement_begin__ = 51;
            context__.validate_dims("data initialization", "intercept_prior_sigma", "double", context__.to_vec());
            intercept_prior_sigma = double(0);
            vals_r__ = context__.vals_r("intercept_prior_sigma");
            pos__ = 0;
            intercept_prior_sigma = vals_r__[pos__++];
            current_statement_begin__ = 52;
            context__.validate_dims("data initialization", "slope_prior_mu", "double", context__.to_vec());
            slope_prior_mu = double(0);
            vals_r__ = context__.vals_r("slope_prior_mu");
            pos__ = 0;
            slope_prior_mu = vals_r__[pos__++];
            current_statement_begin__ = 53;
            context__.validate_dims("data initialization", "slope_prior_sigma", "double", context__.to_vec());
            slope_prior_sigma = double(0);
            vals_r__ = context__.vals_r("slope_prior_sigma");
            pos__ = 0;
            slope_prior_sigma = vals_r__[pos__++];
            current_statement_begin__ = 54;
            context__.validate_dims("data initialization", "sigma_prior_alpha", "double", context__.to_vec());
            sigma_prior_alpha = double(0);
            vals_r__ = context__.vals_r("sigma_prior_alpha");
            pos__ = 0;
            sigma_prior_alpha = vals_r__[pos__++];
            current_statement_begin__ = 55;
            context__.validate_dims("data initialization", "sigma_prior_beta", "double", context__.to_vec());
            sigma_prior_beta = double(0);
            vals_r__ = context__.vals_r("sigma_prior_beta");
            pos__ = 0;
            sigma_prior_beta = vals_r__[pos__++];
            // initialize transformed data variables
            // execute transformed data statements
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 59;
            num_params_r__ += 1;
            current_statement_begin__ = 60;
            num_params_r__ += 1;
            current_statement_begin__ = 61;
            num_params_r__ += 1;
            current_statement_begin__ = 62;
            num_params_r__ += 1;
            current_statement_begin__ = 63;
            num_params_r__ += 1;
            current_statement_begin__ = 64;
            validate_non_negative_index("log2titers1", "N", N);
            num_params_r__ += N;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_lm() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 59;
        if (!(context__.contains_r("intercept")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable intercept missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("intercept");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "intercept", "double", context__.to_vec());
        double intercept(0);
        intercept = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(intercept);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable intercept: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 60;
        if (!(context__.contains_r("slope")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable slope missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("slope");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "slope", "double", context__.to_vec());
        double slope(0);
        slope = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(slope);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable slope: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 61;
        if (!(context__.contains_r("sigma")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable sigma missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("sigma");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "sigma", "double", context__.to_vec());
        double sigma(0);
        sigma = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0.01, sigma);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable sigma: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 62;
        if (!(context__.contains_r("logtiter1mean")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable logtiter1mean missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("logtiter1mean");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "logtiter1mean", "double", context__.to_vec());
        double logtiter1mean(0);
        logtiter1mean = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(logtiter1mean);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable logtiter1mean: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 63;
        if (!(context__.contains_r("logtiter1sd")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable logtiter1sd missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("logtiter1sd");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "logtiter1sd", "double", context__.to_vec());
        double logtiter1sd(0);
        logtiter1sd = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0.01, logtiter1sd);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable logtiter1sd: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 64;
        if (!(context__.contains_r("log2titers1")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable log2titers1 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("log2titers1");
        pos__ = 0U;
        validate_non_negative_index("log2titers1", "N", N);
        context__.validate_dims("parameter initialization", "log2titers1", "vector_d", context__.to_vec(N));
        Eigen::Matrix<double, Eigen::Dynamic, 1> log2titers1(N);
        size_t log2titers1_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < log2titers1_j_1_max__; ++j_1__) {
            log2titers1(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(log2titers1);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable log2titers1: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 59;
            local_scalar_t__ intercept;
            (void) intercept;  // dummy to suppress unused var warning
            if (jacobian__)
                intercept = in__.scalar_constrain(lp__);
            else
                intercept = in__.scalar_constrain();
            current_statement_begin__ = 60;
            local_scalar_t__ slope;
            (void) slope;  // dummy to suppress unused var warning
            if (jacobian__)
                slope = in__.scalar_constrain(lp__);
            else
                slope = in__.scalar_constrain();
            current_statement_begin__ = 61;
            local_scalar_t__ sigma;
            (void) sigma;  // dummy to suppress unused var warning
            if (jacobian__)
                sigma = in__.scalar_lb_constrain(0.01, lp__);
            else
                sigma = in__.scalar_lb_constrain(0.01);
            current_statement_begin__ = 62;
            local_scalar_t__ logtiter1mean;
            (void) logtiter1mean;  // dummy to suppress unused var warning
            if (jacobian__)
                logtiter1mean = in__.scalar_constrain(lp__);
            else
                logtiter1mean = in__.scalar_constrain();
            current_statement_begin__ = 63;
            local_scalar_t__ logtiter1sd;
            (void) logtiter1sd;  // dummy to suppress unused var warning
            if (jacobian__)
                logtiter1sd = in__.scalar_lb_constrain(0.01, lp__);
            else
                logtiter1sd = in__.scalar_lb_constrain(0.01);
            current_statement_begin__ = 64;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> log2titers1;
            (void) log2titers1;  // dummy to suppress unused var warning
            if (jacobian__)
                log2titers1 = in__.vector_constrain(N, lp__);
            else
                log2titers1 = in__.vector_constrain(N);
            // model body
            {
            current_statement_begin__ = 70;
            local_scalar_t__ sigma1(DUMMY_VAR__);
            (void) sigma1;  // dummy to suppress unused var warning
            stan::math::initialize(sigma1, DUMMY_VAR__);
            stan::math::fill(sigma1, DUMMY_VAR__);
            stan::math::assign(sigma1,sigma);
            current_statement_begin__ = 71;
            local_scalar_t__ sigma2(DUMMY_VAR__);
            (void) sigma2;  // dummy to suppress unused var warning
            stan::math::initialize(sigma2, DUMMY_VAR__);
            stan::math::fill(sigma2, DUMMY_VAR__);
            stan::math::assign(sigma2,sigma);
            current_statement_begin__ = 74;
            lp_accum__.add(normal_log<propto__>(intercept, intercept_prior_mu, intercept_prior_sigma));
            current_statement_begin__ = 75;
            lp_accum__.add(normal_log<propto__>(slope, slope_prior_mu, slope_prior_sigma));
            current_statement_begin__ = 76;
            lp_accum__.add(inv_gamma_log<propto__>(sigma1, sigma_prior_alpha, sigma_prior_beta));
            current_statement_begin__ = 77;
            lp_accum__.add(inv_gamma_log<propto__>(sigma2, sigma_prior_alpha, sigma_prior_beta));
            current_statement_begin__ = 78;
            lp_accum__.add(normal_log<propto__>(log2titers1, logtiter1mean, logtiter1sd));
            current_statement_begin__ = 80;
            for (int i = 1; i <= N; ++i) {
                current_statement_begin__ = 83;
                lp_accum__.add(normal_int_censored_likelihood(get_base1(lower_lims1, i, "lower_lims1", 1), get_base1(upper_lims1, i, "upper_lims1", 1), get_base1(log2titers1, i, "log2titers1", 1), sigma1, pstream__));
                current_statement_begin__ = 91;
                lp_accum__.add(normal_int_censored_likelihood(get_base1(lower_lims2, i, "lower_lims2", 1), get_base1(upper_lims2, i, "upper_lims2", 1), ((get_base1(log2titers1, i, "log2titers1", 1) * slope) + intercept), sigma2, pstream__));
            }
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("intercept");
        names__.push_back("slope");
        names__.push_back("sigma");
        names__.push_back("logtiter1mean");
        names__.push_back("logtiter1sd");
        names__.push_back("log2titers1");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_lm_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        double intercept = in__.scalar_constrain();
        vars__.push_back(intercept);
        double slope = in__.scalar_constrain();
        vars__.push_back(slope);
        double sigma = in__.scalar_lb_constrain(0.01);
        vars__.push_back(sigma);
        double logtiter1mean = in__.scalar_constrain();
        vars__.push_back(logtiter1mean);
        double logtiter1sd = in__.scalar_lb_constrain(0.01);
        vars__.push_back(logtiter1sd);
        Eigen::Matrix<double, Eigen::Dynamic, 1> log2titers1 = in__.vector_constrain(N);
        size_t log2titers1_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < log2titers1_j_1_max__; ++j_1__) {
            vars__.push_back(log2titers1(j_1__));
        }
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            if (!include_gqs__ && !include_tparams__) return;
            if (!include_gqs__) return;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    std::string model_name() const {
        return "model_lm";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "intercept";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "slope";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "logtiter1mean";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "logtiter1sd";
        param_names__.push_back(param_name_stream__.str());
        size_t log2titers1_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < log2titers1_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log2titers1" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "intercept";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "slope";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "logtiter1mean";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "logtiter1sd";
        param_names__.push_back(param_name_stream__.str());
        size_t log2titers1_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < log2titers1_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log2titers1" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
    }
}; // model
}  // namespace
typedef model_lm_namespace::model_lm stan_model;
#ifndef USING_R
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
#endif
#endif
