# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("compare_crossreactivity_breadth", "gmt_fixed_sigma", "gmt_me", "gmt", "lm", "logdiff_unpaired_me", "priors", "sr_effects_fixed_sigma", "sr_effects")

# load each stan module
Rcpp::loadModule("stan_fit4compare_crossreactivity_breadth_mod", what = TRUE)
Rcpp::loadModule("stan_fit4gmt_fixed_sigma_mod", what = TRUE)
Rcpp::loadModule("stan_fit4gmt_me_mod", what = TRUE)
Rcpp::loadModule("stan_fit4gmt_mod", what = TRUE)
Rcpp::loadModule("stan_fit4lm_mod", what = TRUE)
Rcpp::loadModule("stan_fit4logdiff_unpaired_me_mod", what = TRUE)
Rcpp::loadModule("stan_fit4priors_mod", what = TRUE)
Rcpp::loadModule("stan_fit4sr_effects_fixed_sigma_mod", what = TRUE)
Rcpp::loadModule("stan_fit4sr_effects_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("rstantools_model_", model_name)))
})
